### PR TITLE
ci: migrate from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by umarcor**
In this PR, CI is migrated from Travis CI to a GitHub Actions workflow, as is. CI will run for any push or PR. Unlike Travis, GitHub Actions is free "without restrictions" for open source (public) projects. At the same time, it should be faster, since installing MSYS2 through chocolatey is avoided. 

Windows execution time:

- On Travis: 28min https://travis-ci.com/github/steveicarus/iverilog/builds/203958045
- On Windows: 31min https://github.com/umarcor/iverilog/runs/1469769023?check_suite_focus=true
- On Windows, without chocolatey: 20min https://github.com/umarcor/iverilog/runs/1469803219?check_suite_focus=true

### CODE REVIEW

**Comment by themperek** [comment]
@umarcor You can also check this: https://github.com/msys2/setup-msys2

**Comment by umarcor** [comment]
@themperek, sure! That's the target. See #398. This PR is the first step for having visible checks without modifying the working scripts. Then, I will transition towards #398. #398 is based on msys2/MINGW-packages, which uses msys2/setup-msys2. In fact, transitioning to setup-msys2 might reduce execution time up to 10min, since packages are cached. Nonetheless, as said, I propose having this merged as is first.

**Comment by steveicarus** [comment]
I saw a conversation about this passing through my email, including the status of Travic-CI. I seem to have accidentally deleted that email chain. I'm inclined to merge this PR, I just want to review the conversation.

**Comment by martinwhitaker** [comment]
@steveicarus, that conversation started in PR #398, which prompted me to open issue #399. Looks like @umarcor has saved me some work :-)

**Comment by steveicarus** [comment]
> @steveicarus, that conversation started in PR #398, which prompted me to open issue #399. Looks like @umarcor has saved me some work :-)

Do we feel like this is ready to merge, then? I would like CI to run at least on PR's for master and the v11-branch branches.

**Comment by martinwhitaker** [comment]
It looks OK to me. It will have the same issue as the old Travis CI if run on the v11 branch - we need to compare against the appropriate expected results file (and generate version-specific expected results for MSYS2). Alternatively we could label all expected failures as such, and modify vvp_reg.pl to return a pass/fail exit code (as I did for vpi_reg.pl).

**Comment by steveicarus** [comment]
Looks like we can create different scripts for different branches. We can use that to pass different expected results to the v11 branch. OK, I'll merge this, then we'll improve it as we get a feel for it.

**Pull request merged**
