### PR TITLE
vvp undriven net initialisation

### PR DESCRIPTION
**Pull request by martinwhitaker**
This is my proposed fix for #1041. Putting it up for review in case anyone can think of a better way (i.e. not requiring a vvp API change).

### CODE REVIEW

**Comment by gatk555** [comment]
I pulled this branch and merged my local changes. It certainly seems to fix #1041. I still have a problem with VPI inputs apparently failing to propagate through ASSIGN, but as attempts to reduce it to a simple test case failed, it is probably my error.

Thanks, G

**Comment by gatk555** [comment]
It seems that my problem with ASSIGNed nets occurs because this PR has uncovered a latent bug in schedule_simulate().
In the attached example, the value of an undriven wire, w, is passed through a gate (using ASSIGN) to another wire that is monitored.  The wire w is then driven periodically by VPI.  With a build of current master, it works as expected, but #1041 shows up as value 'x' rather than '1' at time zero.  With this PR, there is no change at all in the output wire.

The fix seems simple: move the assignment "sim_started = true;" before the call to vpiStartOfSim(). (Patch file included.)
It seems that without that, the first update of the output wire is stranded on schedule_init_list and blocks all later changes.  The regression scripts vvp_reg.pl and vpi_reg.pl still pass with this change.

[test_case2.zip](https://github.com/steveicarus/iverilog/files/13927419/test_case2.zip)

**Comment by martinwhitaker** [comment]
@gatk555 , agreed, that is a latent bug and your fix looks correct. Do you want to be formally credited as the author? If so, we'll either need a git-formatted patch or a separate PR  (but remove the old line, don't just comment it out). If not, I can just give you credit in the commit message.

**Comment by gatk555** [comment]
The simplest thing would be for you to add it to your PR as an additional change, incidental credit is fine.  I did consider making a PR of it, but either that has to wait until yours is committed, or I would have to use your branch as a base, and that would look like stealing.  As a stand-alone change, it does nothing useful, as far as I can tell.

Thanks,
G.

**Comment by larsclausen** [comment]
@martinwhitaker  You can `git commit --author="..."` to assign authorship to somebody else.

**Comment by martinwhitaker** [comment]
@gatk555 , actually it is useful standalone. If you change wire w in your test case to a reg, you'll see the same bug on the master branch. But I'll add it to this PR. Let me know if you want me to use anything other than your GitHub username.

**Comment by gatk555** [comment]
The username is fine.
Thanks, G.

**Review by steveicarus — APPROVED** [review]

**Pull request merged**
