### PR TITLE
Add travis-ci integration (linux + windows)

### PR DESCRIPTION
**Pull request by themperek**
This will add a simple configuration file for free continuous integration service https://travis-ci.org.
It will build and run the ivtest on every commit on linux and windows . It integrates with github and also builds all pull requests giving a status.
Example build log: https://travis-ci.org/themperek/iverilog

It has to be enabled by @steveicarus see:  http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in 

To get proper status for ivtest one need to add exit 0/1 to vvp_reg.pl so travis knows if it passes or not. 

Suggestion:
It is maybe easier to keep it clean when ivtest is part of iverilog repository.

Best Regards,
Tomasz

### CODE REVIEW

**Comment by themperek** [comment]
One can try to add cross-compilation and run the tests under wine.

**Comment by themperek** [comment]
In case anyone would be interested here is a appveyor script witch compiles and runs the tests on windows (free). Unfortunately it takes longer then allowed 40min  for everything.
https://github.com/themperek/iverilog/blob/appveyor/appveyor.yml

Output: https://ci.appveyor.com/project/themperek/iverilog

**Comment by FAIG2014** [comment]
why can't we merge that?

**Comment by eric-wieser** [comment]
@steveicarus, have you had a chance to look at this?

**Comment by themperek** [comment]
Can do with GitHub Actions if this is preferred.

**Comment by steveicarus** [comment]
You know, I simply forgot about this.
Hell with it, I'll just merge it. It can't really be a bad thing.;-)

**Comment by themperek** [comment]
I hope it works still.

@steveicarus 
You have to enable it. https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

**Pull request merged**
