### PR TITLE
Couple of fixes for struct supports

### PR DESCRIPTION
**Pull request by smunaut**
See referenced issues for the problems this PR addresses

### CODE REVIEW

**Comment by caryr** [comment]
Thanks for the patches. Can you please update the eval_tree patch to have the correct spacing (a second level block should be an 8 space tab plus 4 spaces). I do see that the code before the block you added also has a spacing issue and you just followed that, but it would be best to fix the spacing of both your block and the previous block.

We also need to have tests to verify the two fixes are working correctly. It is best to create self checking tests. In general we reserve gold files for tests that we must verify the actual output produced. New tests should be added to the Python based test script.

**Comment by smunaut** [comment]
I wrote the test `.v` files, but I'm not sure in which `.list` file I need to put them TBH.

**Comment by caryr** [comment]
The following covers development topics: https://steveicarus.github.io/iverilog/developer/index.html

The regression section explains how to add tests.

**Comment by caryr** [comment]
This PR resolves #1032 and #1033

**Pull request merged**
